name: Sync main to Bitbucket

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Bitbucket
        env:
          BITBUCKET_REPOWRITE_TOKEN: ${{ secrets.BITBUCKET_REPOWRITE_TOKEN }}
        run: |
          git remote add bitbucket "https://keberflores:${BITBUCKET_REPOWRITE_TOKEN}@bitbucket.org/keberlabs/keber_cl.git"
          git push --force bitbucket main
